--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-07-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SOCIOS_CHUNGOS
--------------------------------------------------------

  CREATE TABLE "HR"."SOCIOS_CHUNGOS" 
   (	"SOCIO_ID" NUMBER, 
	"SOCIO_NAME" VARCHAR2(20 BYTE), 
	"SOCIO_SNAME" VARCHAR2(20 BYTE), 
	"SOCIO_DNI" VARCHAR2(20 BYTE), 
	"SOCIO_FECHA" DATE, 
	"SOCIO_ANTEC" VARCHAR2(20 BYTE), 
	"AFICION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SOCIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SOCIOS_PK" ON "HR"."SOCIOS_CHUNGOS" ("SOCIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SOCIOS_CHUNGOS
--------------------------------------------------------

  ALTER TABLE "HR"."SOCIOS_CHUNGOS" ADD CONSTRAINT "SOCIOS_PK" PRIMARY KEY ("SOCIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."SOCIOS_CHUNGOS" MODIFY ("SOCIO_ANTEC" NOT NULL ENABLE);
  ALTER TABLE "HR"."SOCIOS_CHUNGOS" MODIFY ("SOCIO_ID" NOT NULL ENABLE);
